name: sistema_comisiones_roddome
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+1
  path: ^1.8.0
  path_provider: ^2.0.2
  file_picker: ^5.0.1
  excel: ^2.0.0
  open_file: ^3.2.1


  flutter_lints: ^3.0.0
  msix: ^3.16.7



flutter:

  uses-material-design: true

  assets:
    - assets/
    
